# Generated by Django 6.0.5 on 2026-05-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Dress', 'Dress'), ('Footwear', 'Footwear'), ('Heals', 'Heals'), ('Jwelery', 'Jwelery'), ('Pent', 'Pent'), ('Saree', 'Saree'), ('Shert', 'Shert'), ('Shoes', 'Shoes')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product/')),
                ('description', models.TextField()),
            ],
        ),
    ]
