# Generated by Django 6.0.5 on 2026-06-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_product_discount_product_mainprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='mainprice',
            field=models.IntegerField(default=None),
        ),
    ]
