# Generated by Django 6.0.5 on 2026-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
