# Generated by Django 6.0.5 on 2026-06-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_order_payment_screenshot_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contectmassage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
