# Generated by Django 6.0.5 on 2026-06-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_product_discount_alter_product_mainprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
