# Generated by Django 6.0.5 on 2026-06-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_contectmassage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField(max_length=250)),
                ('city', models.TextField(max_length=250)),
                ('is_seller', models.BooleanField(default=False)),
            ],
        ),
    ]
