# Generated by Django 6.0.5 on 2026-06-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_customermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='password',
            field=models.TextField(default=141),
            preserve_default=False,
        ),
    ]
